language: python

python:
    - "2.7"

sudo: required

services:
    - docker

notifications:
  email:
    recipients:
      - umaganapathyswork@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:

branches:
  only:
    - master

before_install:
    - docker version
    - python --version

install:
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    - git clone https://github.com/kbaseapps/kb_MiniASM.git
    - cd kb_MiniASM

script:
    - kb-sdk validate

after_success:

